app:
  image: pwintermantel/owncloud
  ports:
    - "8001:80"
  links:
    - db
  volumes_from:
    - storage
storage:
  image: busybox
  volumes:
    - /var/lib/postgresql/data 
    - /usr/share/webapps/owncloud/data/
    - /etc/webapps/owncloud/config
  command: true
db:
  image: postgres
  volumes_from:
    - storage
  environment:
    POSTGRES_USER: owncloud
    POSTGRES_PASSWORD: changeme

